services:
  - type: web
    name: slightly_techie_backend_interview
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: ./

    envVars:
      - key: GIN_MODE
        value: release
      - key: PORT
        value: 4000
